name: potato-mall-ci

on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    cache: gradle

            -   name: Verify JDK installation
                run: java -version

            -   name: Set up Gradle
                uses: gradle/actions/setup-gradle@v3
                with:
                    gradle-version: '8.7'

            -   name: Build with Gradle
                run: ./gradlew build -Djasypt.encryptor.password=potatowoong

            -   name: Publish Test Results
                uses: EnricoMi/publish-unit-test-result-action@v2
                if: always()
                with:
                    files: '**/build/test-results/test/TEST-*.xml'
