name: potato-mall-ci

on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    cache: gradle

            -   name: Verify JDK installation
                run: java -version

            -   name: Set up Gradle
                uses: gradle/gradle-build-action@v2
                with:
                    arguments: build
                    cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}

            -   name: Build with Gradle
                run: ./gradlew build -Djasypt.encryptor.password=potatowoong

            -   name: Run tests
                run: ./gradlew test -Djasypt.encryptor.password=potatowoong
