name: potato-mall-ci

on:
    push:
        branches:
            - main
permissions:
    checks: write
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Set up JDK 17
                uses: actions/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    cache: gradle

            -   name: Verify JDK installation
                run: java -version

            -   name: Set up Gradle
                uses: gradle/actions/setup-gradle@v3
                with:
                    gradle-version: '8.7'

            -   name: Build with Gradle
                run: ./gradlew build -Djasypt.encryptor.password=${{secrets.JASYPT_PASSWORD }}

            -   name: Upload Build File
                uses: actions/upload-artifact@v3
                with:
                    name: potato-mall-jar
                    path: ./build/libs/potato-mall.jar

            -   name: Publish Test Results
                uses: mikepenz/action-junit-report@v4
                if: always()
                with:
                    report_paths: '**/build/test-results/test/TEST-*.xml'
                    include_passed: true
    deploy:
        runs-on: ubuntu-latest
        needs: build

        steps:
            -   name: Download Build File
                uses: actions/download-artifact@v3
                with:
                    name: potato-mall-jar

            -   name: ls
                run: ls
